//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioProyectoFinal.ServicioClienteCredito {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioClienteCredito.ServicioClienteCredidoSoap")]
    public interface ServicioClienteCredidoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConsultarCreditoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarCredito", ReplyAction="*")]
        ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoResponse ConsultarCredito(ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarCredito", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoResponse> ConsultarCreditoAsync(ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConsultarTrabajoDesempeñadoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarTrabajoDesempeñado", ReplyAction="*")]
        ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponse ConsultarTrabajoDesempeñado(ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarTrabajoDesempeñado", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponse> ConsultarTrabajoDesempeñadoAsync(ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarCreditoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarCredito", Namespace="http://tempuri.org/", Order=0)]
        public ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoRequestBody Body;
        
        public ConsultarCreditoRequest() {
        }
        
        public ConsultarCreditoRequest(ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsultarCreditoRequestBody {
        
        public ConsultarCreditoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarCreditoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarCreditoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoResponseBody Body;
        
        public ConsultarCreditoResponse() {
        }
        
        public ConsultarCreditoResponse(ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarCreditoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarCreditoResult;
        
        public ConsultarCreditoResponseBody() {
        }
        
        public ConsultarCreditoResponseBody(string ConsultarCreditoResult) {
            this.ConsultarCreditoResult = ConsultarCreditoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarTrabajoDesempeñadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarTrabajoDesempeñado", Namespace="http://tempuri.org/", Order=0)]
        public ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequestBody Body;
        
        public ConsultarTrabajoDesempeñadoRequest() {
        }
        
        public ConsultarTrabajoDesempeñadoRequest(ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarTrabajoDesempeñadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int valor;
        
        public ConsultarTrabajoDesempeñadoRequestBody() {
        }
        
        public ConsultarTrabajoDesempeñadoRequestBody(int valor) {
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarTrabajoDesempeñadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarTrabajoDesempeñadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponseBody Body;
        
        public ConsultarTrabajoDesempeñadoResponse() {
        }
        
        public ConsultarTrabajoDesempeñadoResponse(ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarTrabajoDesempeñadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultarTrabajoDesempeñadoResult;
        
        public ConsultarTrabajoDesempeñadoResponseBody() {
        }
        
        public ConsultarTrabajoDesempeñadoResponseBody(string ConsultarTrabajoDesempeñadoResult) {
            this.ConsultarTrabajoDesempeñadoResult = ConsultarTrabajoDesempeñadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioClienteCredidoSoapChannel : ServicioProyectoFinal.ServicioClienteCredito.ServicioClienteCredidoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClienteCredidoSoapClient : System.ServiceModel.ClientBase<ServicioProyectoFinal.ServicioClienteCredito.ServicioClienteCredidoSoap>, ServicioProyectoFinal.ServicioClienteCredito.ServicioClienteCredidoSoap {
        
        public ServicioClienteCredidoSoapClient() {
        }
        
        public ServicioClienteCredidoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClienteCredidoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteCredidoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteCredidoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoResponse ServicioProyectoFinal.ServicioClienteCredito.ServicioClienteCredidoSoap.ConsultarCredito(ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoRequest request) {
            return base.Channel.ConsultarCredito(request);
        }
        
        public string ConsultarCredito() {
            ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoRequest inValue = new ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoRequest();
            inValue.Body = new ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoRequestBody();
            ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoResponse retVal = ((ServicioProyectoFinal.ServicioClienteCredito.ServicioClienteCredidoSoap)(this)).ConsultarCredito(inValue);
            return retVal.Body.ConsultarCreditoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoResponse> ServicioProyectoFinal.ServicioClienteCredito.ServicioClienteCredidoSoap.ConsultarCreditoAsync(ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoRequest request) {
            return base.Channel.ConsultarCreditoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoResponse> ConsultarCreditoAsync() {
            ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoRequest inValue = new ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoRequest();
            inValue.Body = new ServicioProyectoFinal.ServicioClienteCredito.ConsultarCreditoRequestBody();
            return ((ServicioProyectoFinal.ServicioClienteCredito.ServicioClienteCredidoSoap)(this)).ConsultarCreditoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponse ServicioProyectoFinal.ServicioClienteCredito.ServicioClienteCredidoSoap.ConsultarTrabajoDesempeñado(ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest request) {
            return base.Channel.ConsultarTrabajoDesempeñado(request);
        }
        
        public string ConsultarTrabajoDesempeñado(int valor) {
            ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest inValue = new ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest();
            inValue.Body = new ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequestBody();
            inValue.Body.valor = valor;
            ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponse retVal = ((ServicioProyectoFinal.ServicioClienteCredito.ServicioClienteCredidoSoap)(this)).ConsultarTrabajoDesempeñado(inValue);
            return retVal.Body.ConsultarTrabajoDesempeñadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponse> ServicioProyectoFinal.ServicioClienteCredito.ServicioClienteCredidoSoap.ConsultarTrabajoDesempeñadoAsync(ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest request) {
            return base.Channel.ConsultarTrabajoDesempeñadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoResponse> ConsultarTrabajoDesempeñadoAsync(int valor) {
            ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest inValue = new ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequest();
            inValue.Body = new ServicioProyectoFinal.ServicioClienteCredito.ConsultarTrabajoDesempeñadoRequestBody();
            inValue.Body.valor = valor;
            return ((ServicioProyectoFinal.ServicioClienteCredito.ServicioClienteCredidoSoap)(this)).ConsultarTrabajoDesempeñadoAsync(inValue);
        }
    }
}
